//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocol.proto
namespace pbnetwork
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Connected")]
  public partial class Connected : global::ProtoBuf.IExtensible
  {
    public Connected() {}
    
    private string _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Disconnected")]
  public partial class Disconnected : global::ProtoBuf.IExtensible
  {
    public Disconnected() {}
    
    private string _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private int _error;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error
    {
      get { return _error; }
      set { _error = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private string _legacyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"legacyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string legacyName
    {
      get { return _legacyName; }
      set { _legacyName = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _extraFields = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"extraFields", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> extraFields
    {
      get { return _extraFields; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Logout")]
  public partial class Logout : global::ProtoBuf.IExtensible
  {
    public Logout() {}
    
    private string _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private string _legacyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"legacyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string legacyName
    {
      get { return _legacyName; }
      set { _legacyName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Buddy")]
  public partial class Buddy : global::ProtoBuf.IExtensible
  {
    public Buddy() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _buddyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buddyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string buddyName
    {
      get { return _buddyName; }
      set { _buddyName = value; }
    }

    private string _alias = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"alias", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string alias
    {
      get { return _alias; }
      set { _alias = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _group = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> group
    {
      get { return _group; }
    }
  

    private pbnetwork.StatusType _status = pbnetwork.StatusType.STATUS_ONLINE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(pbnetwork.StatusType.STATUS_ONLINE)]
    public pbnetwork.StatusType status
    {
      get { return _status; }
      set { _status = value; }
    }

    private string _statusMessage = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"statusMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string statusMessage
    {
      get { return _statusMessage; }
      set { _statusMessage = value; }
    }

    private string _iconHash = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iconHash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string iconHash
    {
      get { return _iconHash; }
      set { _iconHash = value; }
    }

    private bool _blocked = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"blocked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool blocked
    {
      get { return _blocked; }
      set { _blocked = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConversationMessage")]
  public partial class ConversationMessage : global::ProtoBuf.IExtensible
  {
    public ConversationMessage() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _buddyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buddyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string buddyName
    {
      get { return _buddyName; }
      set { _buddyName = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }

    private string _xhtml = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"xhtml", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string xhtml
    {
      get { return _xhtml; }
      set { _xhtml = value; }
    }

    private string _timestamp = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }

    private bool _headline = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"headline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool headline
    {
      get { return _headline; }
      set { _headline = value; }
    }

    private string _id = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }

    private bool _pm = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool pm
    {
      get { return _pm; }
      set { _pm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room")]
  public partial class Room : global::ProtoBuf.IExtensible
  {
    public Room() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private string _room;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string room
    {
      get { return _room; }
      set { _room = value; }
    }

    private string _password = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomList")]
  public partial class RoomList : global::ProtoBuf.IExtensible
  {
    public RoomList() {}
    
    private readonly global::System.Collections.Generic.List<string> _room = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> room
    {
      get { return _room; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Participant")]
  public partial class Participant : global::ProtoBuf.IExtensible
  {
    public Participant() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _room;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string room
    {
      get { return _room; }
      set { _room = value; }
    }
    private string _nickname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _flag;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private pbnetwork.StatusType _status;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pbnetwork.StatusType status
    {
      get { return _status; }
      set { _status = value; }
    }

    private string _statusMessage = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"statusMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string statusMessage
    {
      get { return _statusMessage; }
      set { _statusMessage = value; }
    }

    private string _newname = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"newname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string newname
    {
      get { return _newname; }
      set { _newname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VCard")]
  public partial class VCard : global::ProtoBuf.IExtensible
  {
    public VCard() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _buddyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buddyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string buddyName
    {
      get { return _buddyName; }
      set { _buddyName = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _fullname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fullname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fullname
    {
      get { return _fullname; }
      set { _fullname = value; }
    }

    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }

    private byte[] _photo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"photo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] photo
    {
      get { return _photo; }
      set { _photo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Status")]
  public partial class Status : global::ProtoBuf.IExtensible
  {
    public Status() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private pbnetwork.StatusType _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pbnetwork.StatusType status
    {
      get { return _status; }
      set { _status = value; }
    }

    private string _statusMessage = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"statusMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string statusMessage
    {
      get { return _statusMessage; }
      set { _statusMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stats")]
  public partial class Stats : global::ProtoBuf.IExtensible
  {
    public Stats() {}
    
    private int _res;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int res
    {
      get { return _res; }
      set { _res = value; }
    }
    private int _init_res;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"init_res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int init_res
    {
      get { return _init_res; }
      set { _init_res = value; }
    }
    private int _shared;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"shared", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shared
    {
      get { return _shared; }
      set { _shared = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"File")]
  public partial class File : global::ProtoBuf.IExtensible
  {
    public File() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _buddyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buddyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string buddyName
    {
      get { return _buddyName; }
      set { _buddyName = value; }
    }
    private string _fileName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private int _size;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int size
    {
      get { return _size; }
      set { _size = value; }
    }

    private int _ftID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ftID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ftID
    {
      get { return _ftID; }
      set { _ftID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileTransferData")]
  public partial class FileTransferData : global::ProtoBuf.IExtensible
  {
    public FileTransferData() {}
    
    private int _ftID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ftID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ftID
    {
      get { return _ftID; }
      set { _ftID = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackendConfig")]
  public partial class BackendConfig : global::ProtoBuf.IExtensible
  {
    public BackendConfig() {}
    
    private string _config;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string config
    {
      get { return _config; }
      set { _config = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WrapperMessage")]
  public partial class WrapperMessage : global::ProtoBuf.IExtensible
  {
    public WrapperMessage() {}
    
    private pbnetwork.WrapperMessage.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pbnetwork.WrapperMessage.Type type
    {
      get { return _type; }
      set { _type = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_CONNECTED", Value=1)]
      TYPE_CONNECTED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_DISCONNECTED", Value=2)]
      TYPE_DISCONNECTED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_LOGIN", Value=3)]
      TYPE_LOGIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_LOGOUT", Value=4)]
      TYPE_LOGOUT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BUDDY_CHANGED", Value=6)]
      TYPE_BUDDY_CHANGED = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BUDDY_REMOVED", Value=7)]
      TYPE_BUDDY_REMOVED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_CONV_MESSAGE", Value=8)]
      TYPE_CONV_MESSAGE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_PING", Value=9)]
      TYPE_PING = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_PONG", Value=10)]
      TYPE_PONG = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_JOIN_ROOM", Value=11)]
      TYPE_JOIN_ROOM = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_LEAVE_ROOM", Value=12)]
      TYPE_LEAVE_ROOM = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_PARTICIPANT_CHANGED", Value=13)]
      TYPE_PARTICIPANT_CHANGED = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_ROOM_NICKNAME_CHANGED", Value=14)]
      TYPE_ROOM_NICKNAME_CHANGED = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_ROOM_SUBJECT_CHANGED", Value=15)]
      TYPE_ROOM_SUBJECT_CHANGED = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_VCARD", Value=16)]
      TYPE_VCARD = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_STATUS_CHANGED", Value=17)]
      TYPE_STATUS_CHANGED = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BUDDY_TYPING", Value=18)]
      TYPE_BUDDY_TYPING = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BUDDY_STOPPED_TYPING", Value=19)]
      TYPE_BUDDY_STOPPED_TYPING = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BUDDY_TYPED", Value=20)]
      TYPE_BUDDY_TYPED = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_AUTH_REQUEST", Value=21)]
      TYPE_AUTH_REQUEST = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_ATTENTION", Value=22)]
      TYPE_ATTENTION = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_STATS", Value=23)]
      TYPE_STATS = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FT_START", Value=24)]
      TYPE_FT_START = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FT_FINISH", Value=25)]
      TYPE_FT_FINISH = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FT_DATA", Value=26)]
      TYPE_FT_DATA = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FT_PAUSE", Value=27)]
      TYPE_FT_PAUSE = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FT_CONTINUE", Value=28)]
      TYPE_FT_CONTINUE = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_EXIT", Value=29)]
      TYPE_EXIT = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BACKEND_CONFIG", Value=30)]
      TYPE_BACKEND_CONFIG = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_QUERY", Value=31)]
      TYPE_QUERY = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_ROOM_LIST", Value=32)]
      TYPE_ROOM_LIST = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_CONV_MESSAGE_ACK", Value=33)]
      TYPE_CONV_MESSAGE_ACK = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_RAW_XML", Value=34)]
      TYPE_RAW_XML = 34
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ConnectionError")]
    public enum ConnectionError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_NETWORK_ERROR", Value=0)]
      CONNECTION_ERROR_NETWORK_ERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_INVALID_USERNAME", Value=1)]
      CONNECTION_ERROR_INVALID_USERNAME = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_AUTHENTICATION_FAILED", Value=2)]
      CONNECTION_ERROR_AUTHENTICATION_FAILED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_AUTHENTICATION_IMPOSSIBLE", Value=3)]
      CONNECTION_ERROR_AUTHENTICATION_IMPOSSIBLE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_NO_SSL_SUPPORT", Value=4)]
      CONNECTION_ERROR_NO_SSL_SUPPORT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_ENCRYPTION_ERROR", Value=5)]
      CONNECTION_ERROR_ENCRYPTION_ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_NAME_IN_USE", Value=6)]
      CONNECTION_ERROR_NAME_IN_USE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_INVALID_SETTINGS", Value=7)]
      CONNECTION_ERROR_INVALID_SETTINGS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_NOT_PROVIDED", Value=8)]
      CONNECTION_ERROR_CERT_NOT_PROVIDED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_UNTRUSTED", Value=9)]
      CONNECTION_ERROR_CERT_UNTRUSTED = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_EXPIRED", Value=10)]
      CONNECTION_ERROR_CERT_EXPIRED = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_NOT_ACTIVATED", Value=11)]
      CONNECTION_ERROR_CERT_NOT_ACTIVATED = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_HOSTNAME_MISMATCH", Value=12)]
      CONNECTION_ERROR_CERT_HOSTNAME_MISMATCH = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_FINGERPRINT_MISMATCH", Value=13)]
      CONNECTION_ERROR_CERT_FINGERPRINT_MISMATCH = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_SELF_SIGNED", Value=14)]
      CONNECTION_ERROR_CERT_SELF_SIGNED = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_CERT_OTHER_ERROR", Value=15)]
      CONNECTION_ERROR_CERT_OTHER_ERROR = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONNECTION_ERROR_OTHER_ERROR", Value=16)]
      CONNECTION_ERROR_OTHER_ERROR = 16
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StatusType")]
    public enum StatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_ONLINE", Value=0)]
      STATUS_ONLINE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_AWAY", Value=1)]
      STATUS_AWAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_FFC", Value=2)]
      STATUS_FFC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_XA", Value=3)]
      STATUS_XA = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_DND", Value=4)]
      STATUS_DND = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_NONE", Value=5)]
      STATUS_NONE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS_INVISIBLE", Value=6)]
      STATUS_INVISIBLE = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ParticipantFlag")]
    public enum ParticipantFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_NONE", Value=0)]
      PARTICIPANT_FLAG_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_MODERATOR", Value=1)]
      PARTICIPANT_FLAG_MODERATOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_CONFLICT", Value=2)]
      PARTICIPANT_FLAG_CONFLICT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_BANNED", Value=4)]
      PARTICIPANT_FLAG_BANNED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_NOT_AUTHORIZED", Value=8)]
      PARTICIPANT_FLAG_NOT_AUTHORIZED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_ME", Value=16)]
      PARTICIPANT_FLAG_ME = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_KICKED", Value=32)]
      PARTICIPANT_FLAG_KICKED = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PARTICIPANT_FLAG_ROOM_NOT_FOUND", Value=64)]
      PARTICIPANT_FLAG_ROOM_NOT_FOUND = 64
    }
  
}